# Generated by Django 5.0.1 on 2024-02-01 15:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='units',
            new_name='total_stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='web_id',
            field=models.CharField(default=uuid.UUID('316aa8cf-c118-11ee-9c05-ff0c97a402d2'), editable=False, help_text='format: required, unique', max_length=50, unique=True, verbose_name='product website ID'),
        ),
    ]
