# Generated by Django 5.0.1 on 2024-02-01 14:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="web_id",
            field=models.CharField(
                default=uuid.UUID("f6d71352-c10a-11ee-9664-38baf8cd836c"),
                editable=False,
                help_text="format: required, unique",
                max_length=50,
                unique=True,
                verbose_name="product website ID",
            ),
        ),
    ]
