# Generated by Django 5.0.1 on 2024-02-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='web_id',
        ),
    ]
