# Generated by Django 5.0.1 on 2024-02-01 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_product_web_id'),
        ('stock', '0002_rename_units_stock_total_stock_alter_product_web_id'),
    ]

    operations = [
    ]
