# Generated by Django 5.0.1 on 2024-02-01 21:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_merge_20240201_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='web_id',
            field=models.CharField(default=uuid.UUID('f7e24d1f-c147-11ee-a5ec-38baf8cd836c'), editable=False, help_text='format: required, unique', max_length=50, unique=True, verbose_name='product website ID'),
        ),
    ]
