# Generated by Django 5.0.1 on 2024-02-02 13:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0004_alter_product_web_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="web_id",
            field=models.CharField(
                default=uuid.UUID("cb0e9df0-c1cb-11ee-8153-38baf8cd836c"),
                editable=False,
                help_text="format: required, unique",
                max_length=50,
                unique=True,
                verbose_name="product website ID",
            ),
        ),
    ]
