openapi: 3.0.3
info:
  title: Nxt gen hackathone Project API
  version: 0.0.0
paths:
  /stock/product-inventory/:
    get:
      operationId: stock_product_inventory_list
      tags:
      - stock
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductInventory'
          description: ''
  /stock/product-stock/:
    get:
      operationId: stock_product_stock_list
      tags:
      - stock
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductInventoryStock'
          description: ''
  /stock/products/:
    get:
      operationId: stock_products_list
      tags:
      - stock
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
          description: ''
components:
  schemas:
    Product:
      type: object
      properties:
        web_id:
          type: string
          readOnly: true
          title: Product website ID
          description: 'format: required, unique'
        name:
          type: string
          title: Product name
          description: 'format: required, max-255'
          maxLength: 255
        slug:
          type: string
          title: Product safe URL
          description: 'format: required, letters, numbers, underscores or hyphens'
          maxLength: 255
          pattern: ^[-a-zA-Z0-9_]+$
        is_active:
          type: boolean
          title: Product visibility
          description: 'format: true=product visible'
        created_at:
          type: string
          format: date-time
          readOnly: true
          title: Date product created
          description: 'format: Y-m-d H:M:S'
        updated_at:
          type: string
          format: date-time
          readOnly: true
          title: Date product last updated
          description: 'format: Y-m-d H:M:S'
      required:
      - created_at
      - name
      - slug
      - updated_at
      - web_id
    ProductInventory:
      type: object
      properties:
        sku:
          type: string
          title: Stock keeping unit
          description: 'format: required, unique, max-20'
          maxLength: 20
        upc:
          type: string
          title: Universal product code
          description: 'format: required, unique, max-12'
          maxLength: 12
        product:
          $ref: '#/components/schemas/Product'
        product_inventory:
          $ref: '#/components/schemas/ProductInventoryStock'
        product_variant:
          type: string
          maxLength: 255
        is_active:
          type: boolean
          title: Product visibility
          description: 'format: true=product visible'
        purchase_cost:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
          nullable: true
          description: 'format: optional'
        initial_stock:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          description: 'format: required, default-0'
        last_ordered:
          type: string
          format: date-time
          nullable: true
          title: Date last ordered
          description: 'format: Y-m-d H:M:S, optional'
        created_at:
          type: string
          format: date-time
          readOnly: true
          title: Date sub-product created
          description: 'format: Y-m-d H:M:S'
        updated_at:
          type: string
          format: date-time
          readOnly: true
          title: Date sub-product updated
          description: 'format: Y-m-d H:M:S'
      required:
      - created_at
      - product
      - product_inventory
      - product_variant
      - sku
      - upc
      - updated_at
    ProductInventoryStock:
      type: object
      properties:
        last_checked:
          type: string
          format: date-time
          nullable: true
          title: Inventory stock check date
          description: 'format: Y-m-d H:M:S, null-true, blank-true'
        units:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          title: Units/qty of stock
          description: 'format: required, default-0'
        units_out:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          title: Units taken out to date
          description: 'format: required, default-0'
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
