# Generated by Django 5.0.1 on 2024-01-31 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier_name", models.CharField(max_length=255)),
                ("proposal", models.TextField()),
                ("bid_amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="ProcurementChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("open_tendering", "Open Tendering"),
                            ("restricted_tendering", "Restricted Tendering"),
                            ("international_tendering", "International Tendering"),
                            ("rfq", "Request For Quotation RFQ"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicProcurementAct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TenderNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("publication_date", models.DateField(auto_now_add=True)),
                ("closing_date", models.DateField()),
                (
                    "procurement_choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="procurement.procurementchoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcurementProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "selected_bid",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="procurement.bid",
                    ),
                ),
                (
                    "tender_notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="procurement.tendernotice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_text", models.TextField()),
                (
                    "winning_bid",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="procurement.bid",
                    ),
                ),
                (
                    "tender_notice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="procurement.tendernotice",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bid",
            name="tender_notice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="procurement.tendernotice",
            ),
        ),
    ]
