# Generated by Django 5.0.1 on 2024-02-02 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
                ('proposal', models.TextField()),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('open_tendering', 'Open Tendering'), ('restricted_tendering', 'Restricted Tendering'), ('rfq', 'Request For Quotation (RFQ)'), ('single_source', 'Single Source')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PublicProcurementAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=0)),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('closing_date', models.DateField(null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
        ),
        migrations.CreateModel(
            name='RFQbid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.TextField()),
                ('sub_date', models.DateField(auto_now_add=True)),
                ('rfq', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.rfq')),
            ],
        ),
        migrations.CreateModel(
            name='TenderNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('closing_date', models.DateField()),
                ('procurement_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.procurementchoice')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('selected_bid', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.bid')),
                ('tender_notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.tendernotice')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_text', models.TextField()),
                ('winning_bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='procurement.bid')),
                ('tender_notice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='procurement.tendernotice')),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='tender_notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.tendernotice'),
        ),
    ]
