# Generated by Django 5.0.1 on 2024-02-02 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
        ('stock', '0002_remove_product_web_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.productinventory'),
        ),
    ]
