# Generated by Django 5.0.1 on 2024-02-01 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0001_initial"),
        ("stock", "0002_alter_product_web_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tendernotice",
            name="stock",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stock.product",
            ),
        ),
        migrations.AlterField(
            model_name="procurementchoice",
            name="name",
            field=models.CharField(
                choices=[
                    ("open_tendering", "Open Tendering"),
                    ("restricted_tendering", "Restricted Tendering"),
                    ("rfq", "Request For Quotation (RFQ)"),
                    ("single_source", "Single Source"),
                ],
                max_length=255,
            ),
        ),
    ]
