# Generated by Django 5.0.1 on 2024-02-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_alter_rfq_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='budget',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='safety_stock',
            field=models.FloatField(null=True),
        ),
    ]
