# Generated by Django 5.0.1 on 2024-02-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0003_rfq_rfqbid"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfq",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rfq",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rfq",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
